# Generated by Django 4.1.3 on 2022-12-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('choices', models.CharField(choices=[('Taklif', 'Taklif'), ('Shikoyat', 'Shikoyat')], default='Taklif', max_length=8)),
                ('mobile', models.IntegerField(default=9989)),
                ('message', models.TextField(max_length=700)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
