# Generated by Django 4.1.3 on 2022-12-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_myuser_username_alter_myuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
